/* eslint-disable max-len */
import Home from '../pages/Home';

const routes = [
  {
    text: 'Landing',
    name: 'Landing',
    role: ['guest'],
    element: <Home />,
    route: '/',
    parent: 'default',
    icon: 'fa-light fa-home',
  },
  {
    text: 'Home',
    name: 'Home',
    role: ['user'],
    element: <Home />,
    route: '/home',
    parent: 'default',
    icon: 'fa-light fa-home',
  },
  {
    text: 'Records',
    name: 'Records',
    role: ['user'],
    element: <Home />,
    route: '/records',
    parent: 'default',
    icon: 'fa-solid fa-list',
  },
  {
    text: 'Statistics',
    name: 'Statistics',
    role: ['user'],
    element: <Home />,
    route: '/statistics',
    parent: 'default',
    icon: 'fa-solid fa-chart-bar',
  },
  {
    text: 'Planned payments',
    name: 'Planned payments',
    role: ['user'],
    element: <Home />,
    route: '/planned-payments',
    parent: 'default',
    icon: 'fa-solid fa-clock',
  },
  {
    text: 'Budgets',
    name: 'Budgets',
    role: ['user'],
    element: <Home />,
    route: '/budgets',
    parent: 'default',
    icon: 'fa-solid fa-coin',
  },
  {
    text: 'Debts',
    name: 'Debts',
    role: ['user'],
    element: <Home />,
    route: '/debts',
    parent: 'default',
    icon: 'fa-solid fa-hand-holding-usd',
  },
  {
    text: 'Goals',
    name: 'Goals',
    role: ['user'],
    element: <Home />,
    route: '/goals',
    parent: 'default',
    icon: 'fa-solid fa-bullseye',
  },
  {
    text: 'Shopping Lists',
    name: 'Shopping Lists',
    role: ['user'],
    element: <Home />,
    route: '/shopping-lists',
    parent: 'default',
    icon: 'fa-solid fa-cart-shopping',
  },
];

export default routes;
